# 1. Статика из билда
[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = false

# 2. Серверные файлы (uploads)
[[redirects]]
from = "/static/uploads/*"
to = "http://77.110.104.31:3000/static/:splat"
status = 200
force = true

[[redirects]]
from = "/api/file"
to = "http://77.110.104.31:3000/api/file"
status = 200
force = true
methods = ["POST"]

[[redirects]]
from = "/api/file/*"
to = "http://77.110.104.31:3000/api/file/:splat"
status = 200
force = true
methods = ["GET","DELETE"]

# 5. Остальной API
[[redirects]]
from = "/api/*"
to = "http://77.110.104.31:3000/:splat"
status = 200
force = true

# 6. Fallback на index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/pdfjs/*.mjs"
[headers.values]
Content-Type = "application/javascript"
X-Content-Type-Options = "nosniff"