# 1. Статика из билда
[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = false

# 2. Серверные файлы (uploads)
[[redirects]]
from = "/static/uploads/*"
to = "http://77.110.104.31:3000/static/:splat"
status = 200
force = true

# 3. Файловый API: точный путь для POST/DELETE без сплэта
[[redirects]]
from = "/api/file"
to = "http://77.110.104.31:3000/api/file"
status = 200
force = true

# 4. Файловый API: вложенные пути, если используются
[[redirects]]
from = "/api/file/*"
to = "http://77.110.104.31:3000/api/file/:splat"
status = 200
force = true

# 5. Остальной API
[[redirects]]
from = "/api/*"
to = "http://77.110.104.31:3000/:splat"
status = 200
force = true

# 6. Fallback на index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200