# 1. Сначала отдать статику из билда
[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = false

# 2. Затем проксировать server-files
[[redirects]]
from = "/static/uploads/*"
to = "http://77.110.104.31:3000/static/:splat"
status = 200
force = true

# 3. API
[[redirects]]
from = "/api/*"
to = "http://77.110.104.31:3000/:splat"
status = 200
force = true

# 4. Fallback to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200