export const routes = {
  main: "/main",
  login: "/login",
  register: "/register",
  invoices: "/invoices",
  invoicesDetails: "/invoices/:invoiceId/",
  invoicesAddNew: "/invoices/add_new/",
  suppliers: "/suppliers",
  shipments: "/shipments",
  addNewShipments: "/shipments/add_new",
  orders: "/orders",
  ordersDetails: "/orders/:orderId/",
  ordersAddNew: "/orders/add_new/",
  users: "/users",
  profile: "/profile",
  machinery: "/machinery/list",
  addNewMachinery: "/machinery/list/add_new",
  machineryDetails: "/machinery/list/:machineryId/",
  machineryProblems: "/machinery/problems",
  machineryAddProblem: "/machinery/add_problem/:machineryId/",
  machineryTasks: "/machinery/tasks",
  machineryTaskDetails: "/machinery/tasks/:taskId/",
  machineryAddTask: "/machinery/tasks/add_task/:machineryId/",
  machineryComments: "/machinery/comments/",
  machineryMaintenance: "/machinery/maintenance/",
};
